import type { KnowledgeRule, KnowledgeArticle } from './types';

export const MOCK_KNOWLEDGE_RULES: KnowledgeRule[] = [
  {
    id: 'rule-util-30',
    title: 'Keep Credit Utilization Under 30%',
    category: 'credit_health',
    condition: 'credit_utilization > 30%',
    outcome: 'Recommend partial pre-payment before statement generation date.',
    explanation: 'High credit utilization signals risk to rating agencies and negatively impacts CIBIL scores.',
    why: 'CIBIL algorithm assigns a 30% weight to credit utilization ratios.',
    source: 'rbi_policy',
    confidence: 96,
    tags: ['cibil', 'credit_score', 'utilization'],
    priority: 'high',
    active: true,
  },
  {
    id: 'rule-dining-cb',
    title: 'Optimize Dining Spends on Co-branded Cards',
    category: 'dining',
    condition: 'monthly_dining_spend > 5000',
    outcome: 'Switch to a 10% instant discount co-branded dining card.',
    explanation: 'Co-branded dining cards offer up to 10% instant discounts on partner apps compared to 1% standard base rate.',
    why: 'Dining platforms offer exclusive bank merchant agreements.',
    source: 'bank_terms',
    confidence: 92,
    tags: ['dining', 'swiggy', 'cashback'],
    priority: 'high',
    active: true,
  },
  {
    id: 'rule-forex-opt',
    title: 'Use Low Forex Markup Cards for International Spends',
    category: 'travel',
    condition: 'international_travel === true',
    outcome: 'Use cards with 1.5% or 0% forex markup to save conversion fees.',
    explanation: 'Standard cards charge 3.5% + GST on foreign currency transactions whereas premium travel cards charge 1.5% or lower.',
    why: 'RBI regulations allow banks to set competitive forex fees.',
    source: 'rbi_policy',
    confidence: 95,
    tags: ['forex', 'travel', 'international'],
    priority: 'medium',
    active: true,
  },
];

export const MOCK_KNOWLEDGE_ARTICLES: KnowledgeArticle[] = [
  {
    id: 'art-cibil-boost',
    title: 'How to Increase Your CIBIL Score by 50 Points in 90 Days',
    summary: 'Simple steps: maintain <30% credit utilization, automate bill payments, and avoid multiple hard credit inquiries.',
    body: 'Your credit score is calculated based on payment history (35%), credit utilization (30%), length of credit history (15%), credit mix (10%), and new credit inquiries (10%). Automating payments prevents accidental late marks.',
    category: 'credit_health',
    relatedCards: ['card-hdfc-infinia', 'card-sbi-cashback'],
    relatedMerchants: [],
    relatedCategories: ['utilities'],
  },
  {
    id: 'art-smartbuy-miles',
    title: 'Maximizing SmartBuy & Flight Reward Multipliers',
    summary: 'Book flights & hotels through partner portals to earn up to 5× bonus reward points.',
    body: 'Banking partner portals offer accelerated reward multipliers when booking travel directly through dedicated portals.',
    category: 'travel',
    relatedCards: ['card-hdfc-infinia', 'card-axis-atlas'],
    relatedMerchants: ['merch-makemytrip'],
    relatedCategories: ['travel'],
  },
];
