import type { AppNotification } from './types';

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-101',
    type: 'alert',
    priority: 'urgent',
    title: 'Statement Due Date Approaching',
    message: 'Your Infinia statement of ₹45,000 is due in 3 days. Pay early to protect CIBIL score.',
    category: 'billing',
    trigger: 'due_date_3_days_remaining',
    scheduledAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    action: 'Pay Statement Now',
    sourceEngine: 'financial_health',
    status: 'unread',
  },
  {
    id: 'notif-102',
    type: 'opportunity',
    priority: 'high',
    title: 'Amazon 5% Cashback Offer Expiring Soon',
    message: 'Flat 5% instant cashback on electronics expires at midnight tomorrow.',
    category: 'offer',
    trigger: 'offer_expiry_warning',
    scheduledAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    action: 'Claim Cashback Offer',
    sourceEngine: 'merchant_intelligence',
    status: 'unread',
  },
  {
    id: 'notif-103',
    type: 'reminder',
    priority: 'medium',
    title: 'Complete Profile to Unlock 40% Approval Match',
    message: 'Add your city and occupation to complete your profile setup.',
    category: 'health',
    trigger: 'profile_incomplete_reminder',
    scheduledAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    action: 'Update Profile',
    sourceEngine: 'taqdeer',
    status: 'unread',
  },
];
