// @ts-nocheck
import type { CreditCardIntelligence } from './types';

export const MOCK_CARDS_INTELLIGENCE: CreditCardIntelligence[] = [
  {
    id: 'card-hdfc-infinia',
    issuer: 'HDFC Bank',
    network: 'Visa',
    cardName: 'HDFC Infinia Metal Edition',
    annualFee: 12500,
    joiningFee: 12500,
    rewardType: 'points',
    rewardRate: '3.3% base, 5× on SmartBuy (16.5%)',
    loungeAccess: 'Unlimited International & Domestic Lounge Access',
    forexMarkup: 2.0,
    fuelBenefits: '1% surcharge waiver up to ₹1,000/month',
    welcomeBenefits: ['12,500 Reward Points upon fee payment'],
    milestoneBenefits: ['10,000 points on ₹8 Lakh spend per quarter'],
    eligibility: { minSalary: 3000000, minCreditScore: 780 },
    categories: ['travel', 'dining', 'shopping', 'utilities'],
    premiumTier: 'super_premium',
    topBenefit: '16.5% reward rate on flights & hotels via SmartBuy',
  },
  {
    id: 'card-sbi-cashback',
    issuer: 'SBI Card',
    network: 'Visa',
    cardName: 'SBI Cashback Credit Card',
    annualFee: 999,
    joiningFee: 999,
    rewardType: 'cashback',
    rewardRate: '5% online cashback, 1% offline',
    loungeAccess: '4 Domestic visits/year',
    forexMarkup: 3.5,
    fuelBenefits: '1% surcharge waiver',
    welcomeBenefits: ['Fee reversal on ₹2 Lakh annual spend'],
    milestoneBenefits: ['Annual fee waiver on ₹2 Lakh annual spend'],
    eligibility: { minSalary: 30000 },
    categories: ['shopping', 'dining', 'subscriptions'],
    premiumTier: 'entry',
    topBenefit: 'Flat 5% cashback on almost all online spending',
  },
  {
    id: 'card-axis-atlas',
    issuer: 'Axis Bank',
    network: 'Mastercard',
    cardName: 'Axis Bank Atlas Credit Card',
    annualFee: 5000,
    joiningFee: 5000,
    rewardType: 'miles',
    rewardRate: '5 EDGE Miles on Travel, 2 Miles on General',
    loungeAccess: '12 Domestic + 6 International Lounge Visits',
    forexMarkup: 3.5,
    fuelBenefits: '1% surcharge waiver',
    welcomeBenefits: ['5,000 EDGE Miles on 1st transaction within 30 days'],
    milestoneBenefits: ['10,000 bonus EDGE Miles on ₹15 Lakh spend'],
    eligibility: { minSalary: 900000, minCreditScore: 750 },
    categories: ['travel', 'dining'],
    premiumTier: 'premium',
    topBenefit: '1:2 transfer ratio to 10+ Airline & Hotel Loyalty Partners',
  },
  {
    id: 'card-icici-amazon',
    issuer: 'ICICI Bank',
    network: 'Visa',
    cardName: 'Amazon Pay ICICI Card',
    annualFee: 0,
    joiningFee: 0,
    rewardType: 'cashback',
    rewardRate: '5% for Prime, 3% for Non-Prime, 2% digital',
    loungeAccess: 'None',
    forexMarkup: 3.5,
    fuelBenefits: '1% surcharge waiver',
    welcomeBenefits: ['₹1,500 Amazon Pay cashback balance'],
    milestoneBenefits: ['Lifetime Free card with zero fee'],
    eligibility: { minSalary: 25000 },
    categories: ['shopping', 'utilities', 'subscriptions'],
    premiumTier: 'no_fee',
    topBenefit: 'Unlimited 5% cashback on Amazon without upper caps',
  },
  {
    id: 'card-swiggy-hdfc',
    issuer: 'HDFC Bank',
    network: 'Mastercard',
    cardName: 'Swiggy HDFC Bank Credit Card',
    annualFee: 500,
    joiningFee: 500,
    rewardType: 'cashback',
    rewardRate: '10% cashback on Swiggy, 5% online shopping',
    loungeAccess: 'None',
    forexMarkup: 3.5,
    fuelBenefits: '1% surcharge waiver',
    welcomeBenefits: ['3 months Swiggy One membership'],
    milestoneBenefits: ['Annual fee waiver on ₹2 Lakh spend'],
    eligibility: { minSalary: 25000 },
    categories: ['dining', 'shopping'],
    premiumTier: 'entry',
    topBenefit: '10% cashback on Swiggy food & Instamart orders',
  },
  {
    id: 'card-airtel-axis',
    issuer: 'Axis Bank',
    network: 'Visa',
    cardName: 'Airtel Axis Bank Credit Card',
    annualFee: 500,
    joiningFee: 500,
    rewardType: 'cashback',
    rewardRate: '25% on Airtel bills, 10% on Swiggy/Zomato/BigBasket, 10% Utility',
    loungeAccess: '4 Domestic visits/year',
    forexMarkup: 3.5,
    fuelBenefits: '1% surcharge waiver',
    welcomeBenefits: ['₹500 Amazon voucher on 1st transaction'],
    milestoneBenefits: ['Annual fee waiver on ₹2 Lakh spend'],
    eligibility: { minSalary: 30000 },
    categories: ['utilities', 'dining', 'subscriptions'],
    premiumTier: 'entry',
    topBenefit: '25% cashback on Airtel mobile & broadband bills',
  },
  {
    id: 'card-axis-ace',
    issuer: 'Axis Bank',
    network: 'Visa',
    cardName: 'Axis Bank ACE Credit Card',
    annualFee: 499,
    joiningFee: 499,
    rewardType: 'cashback',
    rewardRate: '5% on GPay utility bills, 4% Swiggy/Zomato/Ola, 2% all offline',
    loungeAccess: '4 Domestic visits/year',
    forexMarkup: 3.5,
    fuelBenefits: '1% surcharge waiver',
    welcomeBenefits: ['500 cashback points on activation'],
    milestoneBenefits: ['Annual fee waiver on ₹2 Lakh spend'],
    eligibility: { minSalary: 25000 },
    categories: ['utilities', 'dining', 'general'],
    premiumTier: 'entry',
    topBenefit: '5% cashback on Google Pay utility bill payments',
  },
  {
    id: 'card-tata-neu-infinity',
    issuer: 'HDFC Bank',
    network: 'Rupay',
    cardName: 'Tata Neu Infinity HDFC Credit Card',
    annualFee: 1499,
    joiningFee: 1499,
    rewardType: 'points',
    rewardRate: '5% NeuCoins on Tata Neu, 1.5% UPI & offline',
    loungeAccess: '8 Domestic + 4 International visits/year',
    forexMarkup: 2.0,
    fuelBenefits: '1% surcharge waiver',
    welcomeBenefits: ['1,499 NeuCoins on 1st spend'],
    milestoneBenefits: ['Annual fee waiver on ₹3 Lakh spend'],
    eligibility: { minSalary: 100000 },
    categories: ['shopping', 'travel', 'electronics', 'general'],
    premiumTier: 'mid_tier',
    topBenefit: '1.5% NeuCoins on all RuPay UPI merchant payments',
  },
  {
    id: 'card-bpcl-octane-sbi',
    issuer: 'SBI Card',
    network: 'Visa',
    cardName: 'BPCL SBI Card Octane',
    annualFee: 1499,
    joiningFee: 1499,
    rewardType: 'points',
    rewardRate: '7.25% value back (25X points) at BPCL fuel stations',
    loungeAccess: '4 Domestic visits/year',
    forexMarkup: 3.5,
    fuelBenefits: '7.25% savings up to 2500 points/month',
    welcomeBenefits: ['6,000 Reward Points (₹1,500) on fee payment'],
    milestoneBenefits: ['Annual fee waiver on ₹2 Lakh spend'],
    eligibility: { minSalary: 30000 },
    categories: ['fuel'],
    premiumTier: 'entry',
    topBenefit: '7.25% savings on BPCL petrol, diesel, and lubricant purchases',
  },
  {
    id: 'card-icici-hpcl-super-saver',
    issuer: 'ICICI Bank',
    network: 'Visa',
    cardName: 'ICICI Bank HPCL Super Saver',
    annualFee: 500,
    joiningFee: 500,
    rewardType: 'cashback',
    rewardRate: '5% cashback on HPCL fuel purchases',
    loungeAccess: '1 Domestic visit/quarter',
    forexMarkup: 3.5,
    fuelBenefits: '4% cashback + 1% surcharge waiver at HPCL',
    welcomeBenefits: ['2,000 reward points on activation'],
    milestoneBenefits: ['Annual fee reversal on ₹1.5 Lakh spend'],
    eligibility: { minSalary: 25000 },
    categories: ['fuel', 'utilities'],
    premiumTier: 'entry',
    topBenefit: '5% savings on HPCL fuel & LPG cylinder bookings',
  },
  {
    id: 'card-axis-indian-oil',
    issuer: 'Axis Bank',
    network: 'Rupay',
    cardName: 'IndianOil Axis Bank Credit Card',
    annualFee: 500,
    joiningFee: 500,
    rewardType: 'points',
    rewardRate: '4% value back (20X points) at IOCL outlets',
    loungeAccess: 'None',
    forexMarkup: 3.5,
    fuelBenefits: '1% surcharge waiver + 4% reward points at IOCL',
    welcomeBenefits: ['1,000 EDGE reward points on 1st fuel spend'],
    milestoneBenefits: ['Annual fee waiver on ₹50,000 spend'],
    eligibility: { minSalary: 20000 },
    categories: ['fuel'],
    premiumTier: 'entry',
    topBenefit: '4% rewards at IOCL fuel stations and RuPay UPI support',
  },
  {
    id: 'card-sbi-simplyclick',
    issuer: 'SBI Card',
    network: 'Visa',
    cardName: 'SBI SimplyCLICK Credit Card',
    annualFee: 499,
    joiningFee: 499,
    rewardType: 'points',
    rewardRate: '10X points on Apollo, BookMyShow, Cleartrip, Lenskart, Netmeds',
    loungeAccess: 'None',
    forexMarkup: 3.5,
    fuelBenefits: '1% surcharge waiver',
    welcomeBenefits: ['₹500 Amazon gift voucher'],
    milestoneBenefits: ['Cleartrip voucher worth ₹2,000 on ₹1 Lakh spend'],
    eligibility: { minSalary: 20000 },
    categories: ['shopping', 'entertainment', 'medical', 'subscriptions'],
    premiumTier: 'entry',
    topBenefit: '10X reward points on partner merchants like Apollo, BMS, Netmeds',
  },
  {
    id: 'card-hdfc-regalia-gold',
    issuer: 'HDFC Bank',
    network: 'Visa',
    cardName: 'HDFC Regalia Gold Credit Card',
    annualFee: 2500,
    joiningFee: 2500,
    rewardType: 'points',
    rewardRate: '4 points per ₹150, 5X points on Marks & Spencer, Myntra, Reliance Digital',
    loungeAccess: '12 Domestic + 6 International visits/year',
    forexMarkup: 2.0,
    fuelBenefits: '1% surcharge waiver',
    welcomeBenefits: ['Marks & Spencer / Myntra voucher worth ₹2,500'],
    milestoneBenefits: ['Flight voucher worth ₹5,000 on ₹5 Lakh annual spend'],
    eligibility: { minSalary: 100000 },
    categories: ['travel', 'shopping', 'dining'],
    premiumTier: 'mid_tier',
    topBenefit: '5X rewards on Myntra, Nykaa, and Reliance Digital',
  }
];
