import type { CreditCardIntelligence } from './types';

export const MOCK_CARDS_INTELLIGENCE: CreditCardIntelligence[] = [
  {
    id: 'card-hdfc-infinia',
    issuer: 'HDFC Bank',
    network: 'Visa',
    cardName: 'HDFC Infinia Metal Edition',
    annualFee: 12500,
    joiningFee: 12500,
    rewardType: 'points',
    rewardRate: '3.3% base, 5× on SmartBuy (16.5%)',
    loungeAccess: 'Unlimited International & Domestic Lounge Access',
    forexMarkup: 2.0,
    fuelBenefits: '1% surcharge waiver up to ₹1,000/month',
    welcomeBenefits: ['12,500 Reward Points upon fee payment'],
    milestoneBenefits: ['10,000 points on ₹8 Lakh spend per quarter'],
    eligibility: { minSalary: 3000000, minCreditScore: 780 },
    categories: ['travel', 'dining', 'shopping', 'utilities'],
    premiumTier: 'super_premium',
    topBenefit: '16.5% reward rate on flights & hotels via SmartBuy',
  },
  {
    id: 'card-sbi-cashback',
    issuer: 'SBI Card',
    network: 'Visa',
    cardName: 'SBI Cashback Credit Card',
    annualFee: 999,
    joiningFee: 999,
    rewardType: 'cashback',
    rewardRate: '5% online cashback, 1% offline',
    loungeAccess: '4 Domestic visits/year',
    forexMarkup: 3.5,
    fuelBenefits: '1% surcharge waiver',
    welcomeBenefits: ['Fee reversal on ₹2 Lakh annual spend'],
    milestoneBenefits: ['Annual fee waiver on ₹2 Lakh annual spend'],
    eligibility: { minSalary: 30000 },
    categories: ['shopping', 'dining', 'subscriptions'],
    premiumTier: 'entry',
    topBenefit: 'Flat 5% cashback on almost all online spending',
  },
  {
    id: 'card-axis-atlas',
    issuer: 'Axis Bank',
    network: 'Mastercard',
    cardName: 'Axis Bank Atlas Credit Card',
    annualFee: 5000,
    joiningFee: 5000,
    rewardType: 'miles',
    rewardRate: '5 EDGE Miles on Travel, 2 Miles on General',
    loungeAccess: '12 Domestic + 6 International Lounge Visits',
    forexMarkup: 3.5,
    fuelBenefits: '1% surcharge waiver',
    welcomeBenefits: ['5,000 EDGE Miles on 1st transaction within 30 days'],
    milestoneBenefits: ['10,000 bonus EDGE Miles on ₹15 Lakh spend'],
    eligibility: { minSalary: 900000, minCreditScore: 750 },
    categories: ['travel', 'dining'],
    premiumTier: 'premium',
    topBenefit: '1:2 transfer ratio to 10+ Airline & Hotel Loyalty Partners',
  },
  {
    id: 'card-icici-amazon',
    issuer: 'ICICI Bank',
    network: 'Visa',
    cardName: 'Amazon Pay ICICI Card',
    annualFee: 0,
    joiningFee: 0,
    rewardType: 'cashback',
    rewardRate: '5% for Prime, 3% for Non-Prime, 2% digital',
    loungeAccess: 'None',
    forexMarkup: 3.5,
    fuelBenefits: '1% surcharge waiver',
    welcomeBenefits: ['₹1,500 Amazon Pay cashback balance'],
    milestoneBenefits: ['Lifetime Free card with zero fee'],
    eligibility: { minSalary: 25000 },
    categories: ['shopping', 'utilities', 'subscriptions'],
    premiumTier: 'no_fee',
    topBenefit: 'Unlimited 5% cashback on Amazon without upper caps',
  },
];
