import type { Merchant, MerchantOffer } from './types';

export const MOCK_MERCHANTS: Merchant[] = [
  {
    id: 'merch-amazon',
    name: 'Amazon.in',
    category: 'shopping',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=Amazon',
    website: 'https://amazon.in',
    onlineOffline: 'online',
    supportedPaymentMethods: ['credit_card', 'upi', 'debit_card', 'net_banking'],
    partnerBanks: ['ICICI Bank', 'SBI Card', 'HDFC Bank'],
    tags: ['e-commerce', 'shopping', 'electronics'],
  },
  {
    id: 'merch-swiggy',
    name: 'Swiggy Food & Instamart',
    category: 'dining',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=Swiggy',
    website: 'https://swiggy.com',
    onlineOffline: 'online',
    supportedPaymentMethods: ['credit_card', 'upi', 'debit_card'],
    partnerBanks: ['HDFC Bank', 'Axis Bank', 'ICICI Bank'],
    tags: ['food', 'dining', 'groceries'],
  },
  {
    id: 'merch-makemytrip',
    name: 'MakeMyTrip',
    category: 'travel',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=MakeMyTrip',
    website: 'https://makemytrip.com',
    onlineOffline: 'online',
    supportedPaymentMethods: ['credit_card', 'net_banking'],
    partnerBanks: ['Axis Bank', 'HDFC Bank', 'ICICI Bank'],
    tags: ['travel', 'flights', 'hotels'],
  },
];

export const MOCK_OFFERS: MerchantOffer[] = [
  {
    id: 'off-amazon-5pct',
    merchantId: 'merch-amazon',
    title: '5% Instant Cashback on Amazon Shopping',
    description: 'Get 5% unlimited cashback credited to Amazon Pay on all retail purchases.',
    discountType: 'percentage',
    discountValue: 5,
    eligibleCards: ['card-icici-amazon', 'card-sbi-cashback'],
    eligibleNetworks: ['Visa'],
    minimumSpend: 1000,
    validity: '2026-12-31T23:59:59Z',
    priority: 'high',
    stackable: false,
    category: 'shopping',
  },
  {
    id: 'off-swiggy-10pct',
    merchantId: 'merch-swiggy',
    title: '10% Instant Discount on Swiggy Dining & Instamart',
    description: 'Save 10% up to ₹150 on orders above ₹500 using partner cards.',
    discountType: 'percentage',
    discountValue: 10,
    eligibleCards: ['card-hdfc-infinia', 'card-sbi-cashback'],
    eligibleNetworks: ['Visa', 'Mastercard'],
    minimumSpend: 500,
    validity: '2026-12-31T23:59:59Z',
    priority: 'high',
    stackable: true,
    category: 'dining',
  },
  {
    id: 'off-mmt-flights-15pct',
    merchantId: 'merch-makemytrip',
    title: '15% Off Domestic Flights & 4× Miles',
    description: 'Get up to ₹2,500 instant discount on flight bookings plus 4× reward miles.',
    discountType: 'percentage',
    discountValue: 15,
    eligibleCards: ['card-axis-atlas', 'card-hdfc-infinia'],
    eligibleNetworks: ['Visa', 'Mastercard'],
    minimumSpend: 4000,
    validity: '2026-12-31T23:59:59Z',
    priority: 'high',
    stackable: false,
    category: 'travel',
  },
];
