// @ts-nocheck
import type { Merchant, MerchantOffer } from './types';

export const MOCK_MERCHANTS: Merchant[] = [
  {
    id: 'merch-amazon',
    name: 'Amazon.in',
    category: 'shopping',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=Amazon',
    website: 'https://amazon.in',
    onlineOffline: 'online',
    supportedPaymentMethods: ['credit_card', 'upi', 'debit_card', 'net_banking'],
    partnerBanks: ['ICICI Bank', 'SBI Card', 'HDFC Bank'],
    tags: ['e-commerce', 'shopping', 'electronics'],
  },
  {
    id: 'merch-swiggy',
    name: 'Swiggy Food & Instamart',
    category: 'dining',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=Swiggy',
    website: 'https://swiggy.com',
    onlineOffline: 'online',
    supportedPaymentMethods: ['credit_card', 'upi', 'debit_card'],
    partnerBanks: ['HDFC Bank', 'Axis Bank', 'ICICI Bank'],
    tags: ['food', 'dining', 'groceries'],
  },
  {
    id: 'merch-zomato',
    name: 'Zomato Food Delivery',
    category: 'dining',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=Zomato',
    website: 'https://zomato.com',
    onlineOffline: 'online',
    supportedPaymentMethods: ['credit_card', 'upi', 'debit_card'],
    partnerBanks: ['Axis Bank', 'HDFC Bank', 'ICICI Bank'],
    tags: ['food', 'dining', 'restaurant'],
  },
  {
    id: 'merch-flipkart',
    name: 'Flipkart',
    category: 'shopping',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=Flipkart',
    website: 'https://flipkart.com',
    onlineOffline: 'online',
    supportedPaymentMethods: ['credit_card', 'upi', 'net_banking'],
    partnerBanks: ['Axis Bank', 'ICICI Bank', 'SBI Card'],
    tags: ['shopping', 'e-commerce', 'electronics'],
  },
  {
    id: 'merch-myntra',
    name: 'Myntra Fashion',
    category: 'shopping',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=Myntra',
    website: 'https://myntra.com',
    onlineOffline: 'online',
    supportedPaymentMethods: ['credit_card', 'upi'],
    partnerBanks: ['HDFC Bank', 'ICICI Bank'],
    tags: ['shopping', 'fashion', 'apparel'],
  },
  {
    id: 'merch-makemytrip',
    name: 'MakeMyTrip',
    category: 'travel',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=MakeMyTrip',
    website: 'https://makemytrip.com',
    onlineOffline: 'online',
    supportedPaymentMethods: ['credit_card', 'net_banking'],
    partnerBanks: ['Axis Bank', 'HDFC Bank', 'ICICI Bank'],
    tags: ['travel', 'flights', 'hotels'],
  },
  {
    id: 'merch-irctc',
    name: 'IRCTC Train Booking',
    category: 'travel',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=IRCTC',
    website: 'https://irctc.co.in',
    onlineOffline: 'online',
    supportedPaymentMethods: ['credit_card', 'upi', 'net_banking'],
    partnerBanks: ['SBI Card', 'HDFC Bank'],
    tags: ['travel', 'trains', 'railways'],
  },
  {
    id: 'merch-hpcl',
    name: 'HPCL Fuel Station',
    category: 'fuel',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=HPCL',
    website: 'https://hindustanpetroleum.com',
    onlineOffline: 'both',
    supportedPaymentMethods: ['credit_card', 'upi'],
    partnerBanks: ['ICICI Bank'],
    tags: ['fuel', 'petrol', 'diesel'],
  },
  {
    id: 'merch-iocl',
    name: 'IndianOil Fuel Station',
    category: 'fuel',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=IOCL',
    website: 'https://iocl.com',
    onlineOffline: 'both',
    supportedPaymentMethods: ['credit_card', 'upi'],
    partnerBanks: ['Axis Bank', 'Citi'],
    tags: ['fuel', 'petrol', 'diesel'],
  },
  {
    id: 'merch-bpcl',
    name: 'BPCL Fuel Station',
    category: 'fuel',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=BPCL',
    website: 'https://bharatpetroleum.in',
    onlineOffline: 'both',
    supportedPaymentMethods: ['credit_card', 'upi'],
    partnerBanks: ['SBI Card'],
    tags: ['fuel', 'petrol', 'diesel'],
  },
  {
    id: 'merch-electricity',
    name: 'Electricity Board (BESCOM / State)',
    category: 'utilities',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=Electricity',
    website: 'https://bescom.org.in',
    onlineOffline: 'online',
    supportedPaymentMethods: ['credit_card', 'upi'],
    partnerBanks: ['Axis Bank', 'ICICI Bank'],
    tags: ['utilities', 'electricity', 'bills'],
  },
  {
    id: 'merch-broadband',
    name: 'Airtel Fiber Broadband',
    category: 'utilities',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=Airtel',
    website: 'https://airtel.in',
    onlineOffline: 'online',
    supportedPaymentMethods: ['credit_card', 'upi'],
    partnerBanks: ['Axis Bank'],
    tags: ['utilities', 'broadband', 'telecom', 'bills'],
  },
  {
    id: 'merch-insurance',
    name: 'LIC / HDFC ERGO Insurance',
    category: 'utilities',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=Insurance',
    website: 'https://licindia.in',
    onlineOffline: 'online',
    supportedPaymentMethods: ['credit_card', 'net_banking'],
    partnerBanks: ['HDFC Bank', 'ICICI Bank'],
    tags: ['utilities', 'insurance', 'life_insurance'],
  },
  {
    id: 'merch-gov-payment',
    name: 'Government GST & Tax Portal',
    category: 'utilities',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=Government',
    website: 'https://gst.gov.in',
    onlineOffline: 'online',
    supportedPaymentMethods: ['credit_card', 'net_banking'],
    partnerBanks: ['SBI Card', 'HDFC Bank'],
    tags: ['utilities', 'tax', 'government'],
  },
  {
    id: 'merch-apollo',
    name: 'Apollo Pharmacy & Health',
    category: 'medical',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=Apollo',
    website: 'https://apollopharmacy.in',
    onlineOffline: 'both',
    supportedPaymentMethods: ['credit_card', 'upi'],
    partnerBanks: ['SBI Card'],
    tags: ['medical', 'pharmacy', 'health'],
  },
  {
    id: 'merch-bookmyshow',
    name: 'BookMyShow',
    category: 'entertainment',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=BookMyShow',
    website: 'https://bookmyshow.com',
    onlineOffline: 'online',
    supportedPaymentMethods: ['credit_card', 'upi'],
    partnerBanks: ['SBI Card', 'RBL Bank'],
    tags: ['entertainment', 'movies', 'tickets'],
  },
  {
    id: 'merch-croma',
    name: 'Croma Electronics',
    category: 'shopping',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=Croma',
    website: 'https://croma.com',
    onlineOffline: 'both',
    supportedPaymentMethods: ['credit_card', 'upi'],
    partnerBanks: ['HDFC Bank', 'Tata Neu'],
    tags: ['electronics', 'shopping'],
  },
  {
    id: 'merch-reliance-digital',
    name: 'Reliance Digital',
    category: 'shopping',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=RelianceDigital',
    website: 'https://reliancedigital.in',
    onlineOffline: 'both',
    supportedPaymentMethods: ['credit_card', 'upi'],
    partnerBanks: ['HDFC Bank', 'ICICI Bank'],
    tags: ['electronics', 'shopping'],
  },
  {
    id: 'merch-uber',
    name: 'Uber Rides',
    category: 'travel',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=Uber',
    website: 'https://uber.com',
    onlineOffline: 'online',
    supportedPaymentMethods: ['credit_card', 'upi'],
    partnerBanks: ['Axis Bank'],
    tags: ['travel', 'cab', 'rides'],
  },
  {
    id: 'merch-d-mart',
    name: 'DMart Ready & Supermarket',
    category: 'shopping',
    logo: 'https://api.dicebear.com/7.x/identicon/svg?seed=DMart',
    website: 'https://dmart.in',
    onlineOffline: 'both',
    supportedPaymentMethods: ['credit_card', 'upi'],
    partnerBanks: ['SBI Card', 'ICICI Bank'],
    tags: ['offline_retail', 'groceries', 'supermarket'],
  },
];

export const MOCK_OFFERS: MerchantOffer[] = [
  {
    id: 'off-amazon-5pct',
    merchantId: 'merch-amazon',
    title: '5% Instant Cashback on Amazon Shopping',
    description: 'Get 5% unlimited cashback credited to Amazon Pay on all retail purchases.',
    discountType: 'percentage',
    discountValue: 5,
    eligibleCards: ['card-icici-amazon'],
    eligibleNetworks: ['Visa'],
    minimumSpend: 1000,
    validity: '2026-12-31T23:59:59Z',
    priority: 'high',
    stackable: false,
    category: 'shopping',
  },
  {
    id: 'off-swiggy-10pct',
    merchantId: 'merch-swiggy',
    title: '10% Instant Discount on Swiggy Dining & Instamart',
    description: 'Save 10% up to ₹150 on orders above ₹500 using partner cards.',
    discountType: 'percentage',
    discountValue: 10,
    eligibleCards: ['card-swiggy-hdfc'],
    eligibleNetworks: ['Visa', 'Mastercard'],
    minimumSpend: 500,
    validity: '2026-12-31T23:59:59Z',
    priority: 'high',
    stackable: true,
    category: 'dining',
  },
  {
    id: 'off-zomato-10pct',
    merchantId: 'merch-zomato',
    title: '10% Cashback on Zomato Orders',
    description: 'Get 10% instant discount up to ₹100 on Zomato food delivery.',
    discountType: 'percentage',
    discountValue: 10,
    eligibleCards: ['card-airtel-axis'],
    eligibleNetworks: ['Visa', 'Mastercard'],
    minimumSpend: 400,
    validity: '2026-12-31T23:59:59Z',
    priority: 'high',
    stackable: true,
    category: 'dining',
  },
  {
    id: 'off-mmt-flights-15pct',
    merchantId: 'merch-makemytrip',
    title: '15% Off Domestic Flights & 4× Miles',
    description: 'Get up to ₹2,500 instant discount on flight bookings plus 4× reward miles.',
    discountType: 'percentage',
    discountValue: 15,
    eligibleCards: ['card-axis-atlas'],
    eligibleNetworks: ['Visa', 'Mastercard'],
    minimumSpend: 4000,
    validity: '2026-12-31T23:59:59Z',
    priority: 'high',
    stackable: false,
    category: 'travel',
  },
  {
    id: 'off-bpcl-7pct',
    merchantId: 'merch-bpcl',
    title: '7.25% Value Back on BPCL Fuel',
    description: 'Save 7.25% via 25X reward points on BPCL petrol & diesel.',
    discountType: 'percentage',
    discountValue: 7.25,
    eligibleCards: ['card-bpcl-octane-sbi'],
    eligibleNetworks: ['Visa'],
    minimumSpend: 500,
    validity: '2026-12-31T23:59:59Z',
    priority: 'high',
    stackable: false,
    category: 'fuel',
  },
  {
    id: 'off-hpcl-5pct',
    merchantId: 'merch-hpcl',
    title: '5% Savings on HPCL Fuel & LPG',
    description: 'Save 5% on HPCL fuel purchases and cylinder top-ups.',
    discountType: 'percentage',
    discountValue: 5,
    eligibleCards: ['card-icici-hpcl-super-saver'],
    eligibleNetworks: ['Visa'],
    minimumSpend: 400,
    validity: '2026-12-31T23:59:59Z',
    priority: 'high',
    stackable: false,
    category: 'fuel',
  },
  {
    id: 'off-iocl-4pct',
    merchantId: 'merch-iocl',
    title: '4% Reward Value at IndianOil',
    description: 'Earn 20X EDGE points (4% value) at IOCL outlets.',
    discountType: 'percentage',
    discountValue: 4,
    eligibleCards: ['card-axis-indian-oil'],
    eligibleNetworks: ['Rupay'],
    minimumSpend: 400,
    validity: '2026-12-31T23:59:59Z',
    priority: 'high',
    stackable: false,
    category: 'fuel',
  },
  {
    id: 'off-airtel-25pct',
    merchantId: 'merch-broadband',
    title: '25% Cashback on Airtel Bills',
    description: 'Get 25% instant cashback up to ₹300 per month on Airtel mobile & fiber bills.',
    discountType: 'percentage',
    discountValue: 25,
    eligibleCards: ['card-airtel-axis'],
    eligibleNetworks: ['Visa'],
    minimumSpend: 300,
    validity: '2026-12-31T23:59:59Z',
    priority: 'high',
    stackable: false,
    category: 'utilities',
  },
  {
    id: 'off-utility-5pct',
    merchantId: 'merch-electricity',
    title: '5% Cashback on Electricity Bill Payments',
    description: 'Save 5% cashback on utility payments made via Google Pay.',
    discountType: 'percentage',
    discountValue: 5,
    eligibleCards: ['card-axis-ace', 'card-airtel-axis'],
    eligibleNetworks: ['Visa'],
    minimumSpend: 500,
    validity: '2026-12-31T23:59:59Z',
    priority: 'medium',
    stackable: false,
    category: 'utilities',
  },
  {
    id: 'off-apollo-10x',
    merchantId: 'merch-apollo',
    title: '10X Reward Points at Apollo Pharmacy',
    description: 'Get 10X reward points on all medicines and health products.',
    discountType: 'percentage',
    discountValue: 10,
    eligibleCards: ['card-sbi-simplyclick'],
    eligibleNetworks: ['Visa'],
    minimumSpend: 300,
    validity: '2026-12-31T23:59:59Z',
    priority: 'medium',
    stackable: false,
    category: 'medical',
  },
];
